name: Deploy FastAPI App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Update to checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4  # Update to setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest  # Ensure you have tests; if not, you can comment or remove this step.
    - name: Build Docker image
      run: docker build -t mnist-fastapi-app .
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag mnist-fastapi-app $DOCKER_USERNAME/mnist-fastapi-app
        docker push $DOCKER_USERNAME/mnist-fastapi-app
    - name: Deploy to Render
      run: |
        curl -X POST https://api.render.com/v1/services/srv-csfjjgtds78s738saci0/deploys \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"force": true}'  # You can adjust the body as needed.
